### ISSUE TITLE
Replace with CareUI components in `src/Components/Assets/AssetImportModal.tsx`

### ISSUE THREAD

**Issue by rithviknishad** [rithviknishad/playground#10]
### Tasks

Ensure all the below tasks are accomplished if applicable to the file being modified in the PR.

- [ ] Migrate all Material UI components to use new Care UI / custom components.
- [ ] Migrate all Material UI icons to use `CareIcon`.
- [ ] Migrate `PageTitle` to `Page` component if any.

For more information see the epic issue that tracks this issue.```tsx
1: import { Modal } from "@material-ui/core";
```
